In [1]:
import pandas as pd


mta = pd.read_csv("turnstile_160109.txt")
mta = mta.head(1000)
mta

,C/A,UNIT,SCP,STATION,LINENAME,DIVISION,DATE,TIME,DESC,ENTRIES,EXITS
0,A002,R051,02-00-00,59 ST,NQR456,BMT,01/02/2016,03:00:00,REGULAR,5478180,1849152
1,A002,R051,02-00-00,59 ST,NQR456,BMT,01/02/2016,07:00:00,REGULAR,5478183,1849161
2,A002,R051,02-00-00,59 ST,NQR456,BMT,01/02/2016,11:00:00,REGULAR,5478262,1849240
3,A002,R051,02-00-00,59 ST,NQR456,BMT,01/02/2016,15:00:00,REGULAR,5478519,1849340
4,A002,R051,02-00-00,59 ST,NQR456,BMT,01/02/2016,19:00:00,REGULAR,5478940,1849403
5,A002,R051,02-00-00,59 ST,NQR456,BMT,01/02/2016,23:00:00,REGULAR,5479213,1849445
6,A002,R051,02-00-00,59 ST,NQR456,BMT,01/03/2016,03:00:00,REGULAR,5479279,1849457
7,A002,R051,02-00-00,59 ST,NQR456,BMT,01/03/2016,07:00:00,REGULAR,5479282,1849465
8,A002,R051,02-00-00,59 ST,NQR456,BMT,01/03/2016,11:00:00,REGULAR,5479344,1849513
9,A002,R051,02-00-00,59 ST,NQR456,BMT,01/03/2016,15:00:00,REGULAR,5479558,1849581
10,A002,R051,02-00-00,59 ST,NQR456,BMT,01/03/2016,19:00:00,REGULAR,5479861,1849627
11,A002,R051,02-00-00,59 ST,NQR456,BMT,01/03/2016,23:00:00,REGULAR,5480016,1849650
12,A002,R051,02-00-00,59 ST,NQR456,BMT,01/04/2016,03:00:00,REGULAR,5480037,1849659
13,A002,R051,02-00-00,59 ST,NQR456,BMT,01/04/2016,07:00:00,REGULAR,5480054,1849688
14,A002,R051,02-00-00,59 ST,NQR456,BMT,01/04/2016,11:00:00,REGULAR,5480267,1849999
15,A002,R051,02-00-00,59 ST,NQR456,BMT,01/04/2016,15:00:00,REGULAR,5480499,1850089
16,A002,R051,02-00-00,59 ST,NQR456,BMT,01/04/2016,19:00:00,REGULAR,5481461,1850166
17,A002,R051,02-00-00,59 ST,NQR456,BMT,01/04/2016,23:00:00,REGULAR,5481770,1850206
18,A002,R051,02-00-00,59 ST,NQR456,BMT,01/05/2016,03:00:00,REGULAR,5481795,1850213
19,A002,R051,02-00-00,59 ST,NQR456,BMT,01/05/2016,07:00:00,REGULAR,5481808,1850251
20,A002,R051,02-00-00,59 ST,NQR456,BMT,01/05/2016,11:00:00,REGULAR,5481983,1850609
21,A002,R051,02-00-00,59 ST,NQR456,BMT,01/05/2016,15:00:00,REGULAR,5482235,1850679
22,A002,R051,02-00-00,59 ST,NQR456,BMT,01/05/2016,19:00:00,REGULAR,5483044,1850779
23,A002,R051,02-00-00,59 ST,NQR456,BMT,01/05/2016,23:00:00,REGULAR,5483391,1850820
24,A002,R051,02-00-00,59 ST,NQR456,BMT,01/06/2016,03:00:00,REGULAR,5483436,1850827
25,A002,R051,02-00-00,59 ST,NQR456,BMT,01/06/2016,07:00:00,REGULAR,5483458,1850865
26,A002,R051,02-00-00,59 ST,NQR456,BMT,01/06/2016,11:00:00,REGULAR,5483626,1851260
27,A002,R051,02-00-00,59 ST,NQR456,BMT,01/06/2016,15:00:00,REGULAR,5483826,1851348
28,A002,R051,02-00-00,59 ST,NQR456,BMT,01/06/2016,19:00:00,REGULAR,5484778,1851442
29,A002,R051,02-00-00,59 ST,NQR456,BMT,01/06/2016,23:00:00,REGULAR,5485169,1851501
...,...,...,...,...,...,...,...,...,...,...,...
970,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/02/2016,21:00:00,REGULAR,117728995,513072
971,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/03/2016,01:00:00,REGULAR,117729165,513184
972,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/03/2016,05:00:00,REGULAR,117729185,513198
973,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/03/2016,09:00:00,REGULAR,117729210,513289
974,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/03/2016,13:00:00,REGULAR,117729256,513667
975,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/03/2016,17:00:00,REGULAR,117729534,514314
976,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/03/2016,21:00:00,REGULAR,117729866,514563
977,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/04/2016,01:00:00,REGULAR,117730012,514619
978,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/04/2016,05:00:00,REGULAR,117730017,514620
979,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/04/2016,09:00:00,REGULAR,117730055,515102
980,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/04/2016,13:00:00,REGULAR,117730181,515775
981,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/04/2016,17:00:00,REGULAR,117730595,516284
982,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/04/2016,21:00:00,REGULAR,117731254,516554
983,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/05/2016,01:00:00,REGULAR,117731425,516630
984,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/05/2016,05:00:00,REGULAR,117731429,516634
985,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/05/2016,09:00:00,REGULAR,117731465,517137
986,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/05/2016,13:00:00,REGULAR,117731564,517865
987,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/05/2016,17:00:00,REGULAR,117731948,518297
988,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/05/2016,21:00:00,REGULAR,117732486,518508
989,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/06/2016,01:00:00,REGULAR,117732629,518581
990,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/06/2016,05:00:00,REGULAR,117732639,518596
991,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/06/2016,09:00:00,REGULAR,117732670,519017
992,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/06/2016,13:00:00,REGULAR,117732763,519714
993,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/06/2016,17:00:00,REGULAR,117733240,520137
994,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/06/2016,21:00:00,REGULAR,117733887,520412
995,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/07/2016,01:00:00,REGULAR,117734077,520473
996,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/07/2016,05:00:00,REGULAR,117734085,520477
997,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/07/2016,09:00:00,REGULAR,117734130,520984
998,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/07/2016,13:00:00,REGULAR,117734249,521634
999,A007,R079,01-06-01,5 AV/59 ST,NQR,BMT,01/07/2016,17:00:00,REGULAR,117734650,522065

In [2]:
mta['key'] = zip(mta['C/A'], mta['UNIT'], mta['SCP'], mta['STATION'])

In [7]:
import datetime
mta['datetime'] = pd.to_datetime(mta.DATE + mta.TIME, format='%m/%d/%Y%H:%M:%S')

mta['day'] = pd.to_datetime(mta.DATE, format='%m/%d/%Y')

In [62]:
entries_list = []


for index, row in mta.iterrows():
    if mta['TIME'].iloc[index] == '03:00:00':
        startentries = mta['ENTRIES'].iloc[index]
    if mta['TIME'].iloc[index] == '23:00:00':
        finalentries = mta['ENTRIES'].iloc[index]
        total = finalentries - startentries
        date = mta['day'].iloc[index]
        finaltuple = (date, total)
        entries_list.append(finaltuple)


        
print entries_list

[(Timestamp('2016-01-02 00:00:00'), 1033), (Timestamp('2016-01-03 00:00:00'), 737), (Timestamp('2016-01-04 00:00:00'), 1733), (Timestamp('2016-01-05 00:00:00'), 1596), (Timestamp('2016-01-06 00:00:00'), 1733), (Timestamp('2016-01-07 00:00:00'), 1783), (Timestamp('2016-01-08 00:00:00'), 1853), (Timestamp('2016-01-02 00:00:00'), 904), (Timestamp('2016-01-03 00:00:00'), 669), (Timestamp('2016-01-04 00:00:00'), 1508), (Timestamp('2016-01-05 00:00:00'), 1423), (Timestamp('2016-01-06 00:00:00'), 1459), (Timestamp('2016-01-07 00:00:00'), 1403), (Timestamp('2016-01-08 00:00:00'), 1489), (Timestamp('2016-01-02 00:00:00'), 430), (Timestamp('2016-01-03 00:00:00'), 290), (Timestamp('2016-01-04 00:00:00'), 672), (Timestamp('2016-01-05 00:00:00'), 545), (Timestamp('2016-01-06 00:00:00'), 569), (Timestamp('2016-01-07 00:00:00'), 567), (Timestamp('2016-01-08 00:00:00'), 573), (Timestamp('2016-01-02 00:00:00'), 991), (Timestamp('2016-01-03 00:00:00'), 725), (Timestamp('2016-01-04 00:00:00'), 1250), (Timestamp('2016-01-05 00:00:00'), 1250), (Timestamp('2016-01-06 00:00:00'), 1268), (Timestamp('2016-01-07 00:00:00'), 1328), (Timestamp('2016-01-08 00:00:00'), 1338), (Timestamp('2016-01-02 00:00:00'), 880), (Timestamp('2016-01-03 00:00:00'), 657), (Timestamp('2016-01-04 00:00:00'), 1305), (Timestamp('2016-01-05 00:00:00'), 1258), (Timestamp('2016-01-06 00:00:00'), 1393), (Timestamp('2016-01-07 00:00:00'), 1369), (Timestamp('2016-01-08 00:00:00'), 1408), (Timestamp('2016-01-02 00:00:00'), 873), (Timestamp('2016-01-03 00:00:00'), 629), (Timestamp('2016-01-04 00:00:00'), 1455), (Timestamp('2016-01-05 00:00:00'), 1252), (Timestamp('2016-01-06 00:00:00'), 1406), (Timestamp('2016-01-07 00:00:00'), 1344), (Timestamp('2016-01-08 00:00:00'), 1463), (Timestamp('2016-01-02 00:00:00'), 1009), (Timestamp('2016-01-03 00:00:00'), 696), (Timestamp('2016-01-04 00:00:00'), 1780), (Timestamp('2016-01-05 00:00:00'), 1698), (Timestamp('2016-01-06 00:00:00'), 1888), (Timestamp('2016-01-07 00:00:00'), 1730), (Timestamp('2016-01-08 00:00:00'), 1771), (Timestamp('2016-01-02 00:00:00'), 1592), (Timestamp('2016-01-03 00:00:00'), 1347), (Timestamp('2016-01-04 00:00:00'), 2515), (Timestamp('2016-01-05 00:00:00'), 2482), (Timestamp('2016-01-06 00:00:00'), 2726), (Timestamp('2016-01-07 00:00:00'), 2775), (Timestamp('2016-01-08 00:00:00'), 2745), (Timestamp('2016-01-02 00:00:00'), 1068), (Timestamp('2016-01-03 00:00:00'), 854), (Timestamp('2016-01-04 00:00:00'), 2216), (Timestamp('2016-01-05 00:00:00'), 2263), (Timestamp('2016-01-06 00:00:00'), 2388), (Timestamp('2016-01-07 00:00:00'), 2454), (Timestamp('2016-01-08 00:00:00'), 2325), (Timestamp('2016-01-02 00:00:00'), 0), (Timestamp('2016-01-03 00:00:00'), 1), (Timestamp('2016-01-04 00:00:00'), 0), (Timestamp('2016-01-05 00:00:00'), 0), (Timestamp('2016-01-06 00:00:00'), 0), (Timestamp('2016-01-07 00:00:00'), 0), (Timestamp('2016-01-08 00:00:00'), 0), (Timestamp('2016-01-02 00:00:00'), 0), (Timestamp('2016-01-03 00:00:00'), 0), (Timestamp('2016-01-04 00:00:00'), 0), (Timestamp('2016-01-05 00:00:00'), 0), (Timestamp('2016-01-06 00:00:00'), 0), (Timestamp('2016-01-07 00:00:00'), 0), (Timestamp('2016-01-08 00:00:00'), 0), (Timestamp('2016-01-02 00:00:00'), 1176), (Timestamp('2016-01-03 00:00:00'), 932), (Timestamp('2016-01-04 00:00:00'), 2224), (Timestamp('2016-01-05 00:00:00'), 2174), (Timestamp('2016-01-06 00:00:00'), 2444), (Timestamp('2016-01-07 00:00:00'), 2525), (Timestamp('2016-01-08 00:00:00'), 2482)]